from django.urls import path,include
from .import views
urlpatterns = [
    path('',views.ho,name='ho'),
    path('log',views.log,name='log'),
    path('sign',views.sign,name='sign'),
    path('adm',views.adm,name='adm'),
    path('use',views.use,name='use'),
    path('hlog',views.hlog,name='hlog'),
    path('add_usr',views.add_usr,name='add_usr'),
    path('cate',views.cate,name='cate'),
    path('adcate',views.adcate,name='adcate'),
    path('prod',views.prod,name='prod'),
    path('adpro',views.adpro,name='adpro'),
    path('test',views.test,name='test'),
    path('show_prod',views.show_prod,name='show_prod'),
    path('show_users',views.show_users,name='show_users'),
    path('men',views.men,name='men'),
    path('women',views.women,name='women'),
    path('us_home',views.us_home,name='us_home'),
    path('prolist/<int:k>',views.prolist,name='prolist'),
    path('pro_list',views.pro_list,name='pro_list'),
    path('cart/<int:k>',views.cart,name='cart'),
    path('logout',views.logout,name='logout'),
    path('deletepro/<int:k>',views.deletepro,name='deletepro'),
    path('deleteusr/<int:k>',views.deleteusr,name='deleteusr'),
    path('increase/<int:k>',views.increase,name='increase'),
    path('decrease/<int:k>',views.decrease,name='decrease'),
    path('remove/<int:k>',views.remove,name='remove'),
    path('cartde',views.cartde,name='cartde'),
    path('cart1',views.cart1,name='cart1'),
]